version: '3.8'

services:
  backend:
    build:
      context: ./backend/expBanking  # Adjust this path to your backend Dockerfile location
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/expbanking
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/exp-banking/  # Adjust this path to your frontend Dockerfile location
      dockerfile: Dockerfile
    ports:
      - "5173:80"  # Adjust this port if your frontend uses a different port
    environment:
      - VITE_DB_API_KEY=http://backend:8080/
      - VITE_ADMIN_EMAIL=admin@gmail.com
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=expbanking
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: