services:
  - type: web
    name: exp-banking-backend
    env: docker
    dockerfilePath: ./backend/expBanking/Dockerfile
    dockerContext: ./backend/expBanking
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: postgresql://postgresql_expbanking_user:XAJXGKdSHPo1a37N63USeAYsTewxEbwT@dpg-cs78rit6l47c7393ptfg-a/postgresql_expbanking

  - type: web
    name: exp-banking-frontend
    env: docker
    dockerfilePath: ./frontend/exp-banking/Dockerfile
    dockerContext: ./frontend/exp-banking
